---
- hosts: workers
  become: true
  become_user: root
  roles:
    - marverix.chromium
    - wunzeco.google-chrome
  tasks:
  - name: Install Git
    yum:
     name: git
     state: present
  - name: Install Docker
    yum: name=docker state=installed
  - name: Start Docker services
    service: name=docker state=started
  - name: Create directory for Docker files
    file:
      path: /root/docker-certproject
      state: directory
  - git:
     repo: 'https://github.com/edureka-devops/projCert.git'
     dest: /var/www/php
  - git:
     repo: 'https://github.com/edureka-devops/Selenium_module.git'
     dest: /devops/projCert/Selenium_module
  - git:
     repo: 'https://github.com/edureka-devops/projDock.git'
     dest: /devops/projCert/docker/dockerfile


