---
- hosts: workers
  become: true
  become_user: root
  tasks:
  - name: Install Docker
    yum: name=docker state=installed
  - name: Start Docker services
    service: name=docker state=started
  - name: Create directory for Docker files
    file: path=/root/docker-certproject state=directory
  - name: Install git
    yum: name=git state=installed
  roles:
    - koichirok.chromedriver
