---
- hosts: workers
  become: true
  become_user: ansible
  tasks:
  - name: Install Docker
    yum: name=docker state=installed
  - name: Start Docker services
    service: name=docker state=started
  - name: Create directory for Docker files
    file: path=/root/docker-certproject state=directory
